// Brands available for baby product categories
// These brands are optional when adding/editing products

export const BRAND_OPTIONS = {
  "Strollers & Travel": [
    "Chicco",
    "Graco",
    "Cybex",
    "Bugaboo",
    "Joie",
    "Maclaren",
    "Phil & Teds",
    "Silver Cross",
    "Cosatto",
    "Uppababy",
    "Nuna",
    "Kidilo",
    "Other",
  ],
  "Car Seats": [
    "Chicco",
    "Graco",
    "Cybex",
    "Joie",
    "Maxi-Cosi",
    "Britax",
    "Nuna",
    "Clek",
    "Doona",
    "Uppababy",
    "Kidilo",
    "Other",
  ],
  "Carry Cot": [
    "Chicco",
    "Graco",
    "Joie",
    "Cybex",
    "Nuna",
    "Phil & Teds",
    "Bugaboo",
    "Kidilo",
    "Other",
  ],
  "Bed": [
    "Chicco",
    "Graco",
    "Babymore",
    "SnuzPod",
    "Tutti Bambini",
    "Stokke",
    "Uppababy",
    "Kidilo",
    "Other",
  ],
  "Feeding & Nursing": [
    "Philips Avent",
    "Tommee Tippee",
    "Medela",
    "Dr. Brown's",
    "Chicco",
    "MAM",
    "Pigeon",
    "NUK",
    "Lansinoh",
    "Spectra",
    "Willow",
    "Elvie",
    "Haakaa",
    "Bellababy",
    "Momcozy",
    "Kidilo",
    "Other",
  ],
  "Bouncers & Swings": [
    "Chicco",
    "Fisher-Price",
    "Graco",
    "Ingenuity",
    "Joie",
    "Babybjörn",
    "4moms",
    "Kidilo",
    "Other",
  ],
  "High Chairs": [
    "Chicco",
    "Graco",
    "Joie",
    "Stokke",
    "Nuna",
    "Peg Perego",
    "Cosatto",
    "Kidilo",
    "Other",
  ],
  "Toys & Play": [
    "Fisher-Price",
    "LEGO",
    "Playskool",
    "Bright Starts",
    "Lamaze",
    "VTech",
    "Infantino",
    "Tomy",
    "Kidilo",
    "Other",
  ],
  "Electronics & Monitors": [
    "Philips Avent",
    "Motorola",
    "VTech",
    "HelloBaby",
    "Cocoo Care",
    "Summer",
    "Owlet",
    "Nanit",
    "Miku",
    "Cubo AI",
    "Angelcare",
    "Levana",
    "Momcozy",
    "Kidilo",
    "Other",
  ],
  "Baby Walker": [
    "Chicco",
    "Fisher-Price",
    "Bright Starts",
    "Safety 1st",
    "Joie",
    "Babymoov",
    "Kidilo",
    "Other",
  ],
};

export function getBrandOptions(category) {
  return BRAND_OPTIONS[category] || [];
}

export function hasBrandOption(category) {
  return !!BRAND_OPTIONS[category];
}
